# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.2.1
    steps:
      - checkout
      - run: npm install
      # run tests!
      - run: npm test --runInBand
      - run:
            name: Jest Suite
                  command: yarn jest -- --ci --testResultsProcessor="jest-junit"
                  environment:
                    JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: path: reports/junit
